- name: Create .kube directory
  become: true
  file:
    path: "/home/{{ main_user }}/.kube"
    state: directory
    mode: 0700
    owner: "{{ main_user }}"
    group: "{{ main_user }}"

- name: Setup kubeconfig for user
  become: true
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ main_user }}/.kube/config"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0600
