- name: Post installation update
  include_role: name=packages tasks_from=update

- name: Manage user
  include_role: name=users

- name: Harden OS
  include_role: name=dev-sec.os-hardening

- name: Harden SSH
  include_role: name=dev-sec.ssh-hardening
