- name: Activate rescue system
  uri:
    url: "{{ base_url }}/boot/{{ ansible_host }}/rescue"
    method: POST
    user: "{{ hetzner.username }}"
    password: "{{ hetzner.password }}"
    body_format: form-urlencoded
    body: "os={{ hetzner.os | default('linux') }}&arch={{ hetzner.arch | default(64) }}&authorized_key={{ hetzner.fingerprint }}"
    status_code: 200
