- name: Make helm 3
  become: true
  command: make helm
  args:
    chdir: "/home/{{ main_user }}/node-launcher/"
    creates: /usr/local/bin/helm

- name: Modify helm executable
  become: true
  file:
    path: /usr/local/bin/helm
    mode: a+rx
